### ISSUE TITLE
打开 关闭实时预览失效

### ISSUE THREAD

**Issue by libinworks** [Chave-Z/le-markdown-editor#2]
如题  ‘眼睛按钮不好使’  试了几个浏览器都不行

**Comment by Chave-Z** [comment]
恩 已经更新了



在 2020-02-14 15:21:52，"李斌" <notifications@github.com> 写道：

如题 ‘眼睛按钮不好使’ 试了几个浏览器都不行

**Comment by Chave-Z** [comment]
这是之前0.0.6版本更新时出的问题 ，这个我已经在2020-03-08发现并更新了，你得看版本是不是到0.0.7了，如果这边的代码你试了还是没用  你可以到码云上看看 https://gitee.com/Chave-Z/le-markdown-editor  这边我就是做同步仓库的，可能没更新上，
