### ISSUE TITLE
应该把预览组件单独拆出来一个

### ISSUE THREAD

**Issue by yuanjunliang** [Chave-Z/le-markdown-editor#3]
现在编辑可以了，但是前端展示的时候不应该显示编辑器。所以建议吧预览组件单独拆出来

**Comment by Chave-Z** [comment]
你指的是使用的时候显示是吧 这个其实把保存获取到的html外面套一个<div class="markdown-body"></div>就行 但是要引入一下样式表 不过既然说到了 我觉得这是一个好想法 我这几天添加一下

**Comment by Chave-Z** [comment]
上周已实现
