### ISSUE TITLE
在添加代码的时候使用tab键缩进样式问题

### ISSUE THREAD

**Issue by toplyb** [Chave-Z/le-markdown-editor#9]
- 确实是一款不错的`Markdown`编辑器,找了很久觉得这个是最顺手的
---
- 问题描述:
   - 在其中添加代码的时候(比如添加`PHP`代码)的时候,发现使用`tab`键缩进的距离和用四个空格缩进的距离并不一样,当用`tab`键缩进的时候,大概是会产生8个空格的距离,并不是4个
   - 错误的样式如下:
   ```php
   <?php
   class Human{
            public function ceshi()   // 此行是使用了1个tab键的样式
        {   // 两个大括号样式正确是因为使用了4个空格
    	return ceshi;
        }
   }
   ```
---
- 可能描述的不是很清楚,辛苦作者查看一下(ps:希望您可以一直维护)

**Comment by Chave-Z** [comment]
> * 确实是一款不错的`Markdown`编辑器,找了很久觉得这个是最顺手的
> 
> * 问题描述:
>   
>   * 在其中添加代码的时候(比如添加`PHP`代码)的时候,发现使用`tab`键缩进的距离和用四个空格缩进的距离并不一样,当用`tab`键缩进的时候,大概是会产生8个空格的距离,并不是4个
>   * 错误的样式如下:
>   
>   ```
>   <?php
>   class Human{
>            public function ceshi()   // 此行是使用了1个tab键的样式
>        {   // 两个大括号样式正确是因为使用了4个空格
>    	return ceshi;
>        }
>   }
>   ```
> 
> * 可能描述的不是很清楚,辛苦作者查看一下(ps:希望您可以一直维护)

感谢你的支持，首先项目肯定会一直维护的，这半年来因为项目一直很忙，很多时候还都是内网环境，一直没更新。最近刚缓下来，这两天加了点功能，然后今天更新完1.1.3的版本才看到这个，刚刚已经处理了，1.1.4版本会更新（这几天就会发版，需要处理一下xss问题）。要是你还在关注，欢迎到时候体验
